name: Student_Project_n

dependencies:
- numpy
- pandas
- pandas 
- jupyterlab
- matplotlib
- seaborn
- scipy
- pip:
  - grmpy
  - sklearn
  - graphviz
  - IPython
  - statsmodels
  - seaborn
  - pydlm
